username: Mumblecop
password:
address: localhost
triggers: ['mumblecop', 'mc', 'mc', 'mb']
comment: 'I am a robot beep boop'
initial-volume: 5
use-mpd: false
mpd-pipe-location: '/tmp/mpd.fifo'
mpd-port: 6600
mpd-address: localhost
plugin-update-rate: 0.1
plugins:
  volume:
    min_volume: 5 
